# Generated by Django 2.2.3 on 2019-07-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fullname',
            field=models.CharField(default='Smarty McPants', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='link',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='pubdate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onlineappendices',
            name='associatedpaper',
            field=models.CharField(default='Extra Goodness', max_length=200),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(default='Fire Research', max_length=200),
        ),
    ]
